# Generated by Django 5.2.8 on 2025-11-27 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_interviewresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='role',
            field=models.CharField(default='general', max_length=100),
        ),
        migrations.AddField(
            model_name='question',
            name='skill',
            field=models.CharField(default='general', max_length=100),
        ),
    ]
