# Generated by Django 5.2.8 on 2025-11-29 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_question_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewresult',
            name='session_id',
            field=models.CharField(default='unknown', max_length=200),
        ),
        migrations.AlterField(
            model_name='question',
            name='level',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='question',
            name='role',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='question',
            name='skill',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
